### Регистрация
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username": "Sultan",
  "email": "astromidand2929@gmail.com",
  "password": "1234"
}

### Авторизц
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "astromidand2929@gmail.com",
  "password": "1234"
}



### Создать задачу (To-Do)
POST http://localhost:5000/execution/task
Content-Type: application/json
Authorization: Bearer 

{
  "text": "Выучить JWT и ToDo проект"
}


### Получить все задачи
GET http://localhost:5000/execution/tasks
Authorization: Bearer 


### Обновить задачу по id 
PUT http://localhost:5000/execution/tasks/
Content-Type: application/json
Authorization: Bearer 

{
  "text": "Обновлённая задача3",
  "completed": true
}


###Удалить задачу по id
DELETE http://localhost:5000/execution/tasks/
Authorization: Bearer 


### Проверка защищённого маршрута
GET http://localhost:5000/auth/profile
Authorization: Bearer 